#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-pdf-reader
Version  : 1.4.0
Release  : 6
URL      : https://rubygems.org/downloads/pdf-reader-1.4.0.gem
Source0  : https://rubygems.org/downloads/pdf-reader-1.4.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-pdf-reader-bin
BuildRequires : ruby
BuildRequires : rubygem-Ascii85
BuildRequires : rubygem-ZenTest
BuildRequires : rubygem-ir_b
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-ruby-rc4
BuildRequires : rubygem-ttfunk

%description
= Release Notes
The PDF::Reader library implements a PDF parser conforming as much as possible
to the PDF specification from Adobe.

%package bin
Summary: bin components for the rubygem-pdf-reader package.
Group: Binaries

%description bin
bin components for the rubygem-pdf-reader package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n pdf-reader-1.4.0
gem spec %{SOURCE0} -l --ruby > rubygem-pdf-reader.gemspec

%build
gem build rubygem-pdf-reader.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
pdf-reader-1.4.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/pdf-reader-1.4.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/CHANGELOG
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/MIT-LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/TODO
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/bin/pdf_callbacks
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/bin/pdf_list_callbacks
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/bin/pdf_object
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/bin/pdf_text
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/examples/callbacks.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/examples/extract_bates.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/examples/extract_fonts.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/examples/extract_images.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/examples/hash.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/examples/metadata.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/examples/page_count.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/examples/rspec.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/examples/text.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/examples/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf-reader.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/hash.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/abstract_strategy.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/afm/Courier-Bold.afm
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/afm/Courier-BoldOblique.afm
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/afm/Courier-Oblique.afm
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/afm/Courier.afm
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/afm/Helvetica-Bold.afm
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/afm/Helvetica-BoldOblique.afm
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/afm/Helvetica-Oblique.afm
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/afm/Helvetica.afm
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/afm/Symbol.afm
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/afm/Times-Bold.afm
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/afm/Times-BoldItalic.afm
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/afm/Times-Italic.afm
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/afm/Times-Roman.afm
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/afm/ZapfDingbats.afm
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/buffer.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/cid_widths.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/cmap.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/encoding.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/encodings/mac_expert.txt
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/encodings/mac_roman.txt
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/encodings/pdf_doc.txt
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/encodings/standard.txt
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/encodings/symbol.txt
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/encodings/win_ansi.txt
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/encodings/zapf_dingbats.txt
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/error.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/filter/ascii85.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/filter/ascii_hex.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/filter/depredict.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/filter/flate.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/filter/lzw.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/filter/null.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/filter/run_length.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/font.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/font_descriptor.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/form_xobject.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/glyph_hash.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/glyphlist.txt
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/lzw.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/metadata_strategy.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/object_cache.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/object_hash.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/object_stream.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/orientation_detector.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/page.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/page_layout.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/page_state.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/page_text_receiver.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/pages_strategy.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/parser.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/print_receiver.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/reference.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/register_receiver.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/resource_methods.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/standard_security_handler.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/stream.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/synchronized_cache.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/text_receiver.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/text_run.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/token.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/transformation_matrix.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/width_calculator.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/width_calculator/built_in.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/width_calculator/composite.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/width_calculator/true_type.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/width_calculator/type_one_or_three.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/width_calculator/type_zero.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-reader-1.4.0/lib/pdf/reader/xref.rb
/usr/lib64/ruby/gems/2.3.0/specifications/pdf-reader-1.4.0.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/pdf_callbacks
/usr/bin/pdf_list_callbacks
/usr/bin/pdf_object
/usr/bin/pdf_text
